#! /bin/bash

# pegs/ios-build-server

fancy_echo "Adding Jenkins..."
brew cask install java

if [ ! brew list | grep jenkins ]; then
    brew install jenkins
fi

# update the jenkins config file with the port supplied
sed -ie "s/--httpPort=[0-9][0-9]*/--httpPort=$JENKINSPORT/" `find /usr/local/Cellar/jenkins -name homebrew.mxcl.jenkins.plist`

# probably need to do about the same thing to set up the listening address

brew services start jenkins

